export default {
    THEME_CHANGE: "THEME_CHANGE",
    SHOW_THEME_VIEW: "SHOW_THEME_VIEW",
    POPULAR_REFRESH: "POPULAR_REFRESH",
    POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL",
    POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",
    LOAD_POPULAR_SUCCESS: "LOAD_POPULAR_SUCCESS",

}
